### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OzgunKB** [Snaacky/Diamond#9]
Not working...

`Diamond has launched.
AdjustTokenPrivileges error: 0x00000006

2020-06-04 18:38:50,241 - pymem - DEBUG - Process 24276 is being debugged
Traceback (most recent call last):
  File "diamond.py", line 41, in <module>
    main()
  File "diamond.py", line 13, in main
    client = pymem.process.module_from_name(pm.process_handle, "client_panorama.dll").lpBaseOfDll
AttributeError: 'NoneType' object has no attribute 'lpBaseOfDll'`

**Comment by Snaacky** [comment]
Valve renamed client_panorma.dll to client.dll. Fixed in commit ddf1ea0a41379d6493a1d979593a023f73957502. Thanks for the report.
